(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ag-highlight-search t)
 '(ag-reuse-buffers t)
 '(ag-reuse-window t)
 '(auctex-package t)
 '(auto-hscroll-mode t)
 '(c-echo-syntactic-information-p t)
 '(c-electric-pound-behavior (quote (alignleft)))
 '(c-indent-comments-syntactically-p t)
 '(c-support-package t)
 '(calc-package t)
 '(calendar-package t)
 '(cc-mode-package t)
 '(column-number-mode t)
 '(cookie-package t)
 '(crisp-package t)
 '(custom-file "~/.emacs.d/customizations.el")
 '(debug-package t)
 '(delete-key-deletes-forward t)
 '(diff-hl-draw-borders t)
 '(dired-package t)
 '(display-battery-mode nil)
 '(display-time-24hr-format t)
 '(display-time-mode t)
 '(ediff-package t)
 '(edit-utils-package t)
 '(electric-pair-mode t)
 '(emerge-package t)
 '(eterm-package t)
 '(eudc-package t)
 '(font-lock-mode t t (font-lock))
 '(font-lock-use-colors t)
 '(font-lock-use-fonts nil)
 '(frame-background-mode (quote dark))
 '(frame-icon-package nil)
 '(fringe-mode (quote (nil . 0)) nil (fringe))
 '(fsf-compat-package t)
 '(global-display-line-numbers-mode t)
 '(global-hl-line-mode t)
 '(horizontal-scroll-bar-mode nil)
 '(igrep-package t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-buffer-menu t)
 '(inhibit-startup-echo-area-message "kmb")
 '(inhibit-startup-screen t)
 '(initial-buffer-choice t)
 '(initial-major-mode (quote text-mode))
 '(initial-scratch-message nil)
 '(ispell-extra-args (quote ("--reverse")))
 '(ispell-package t)
 '(ispell-program-name "aspell")
 '(magit-commit-arguments (quote ("--gpg-sign=1C36852961D1F07A")))
 '(magit-completing-read-function (quote magit-ido-completing-read))
 '(magit-log-arguments (quote ("--graph" "--decorate" "--show-signature" "-n256")))
 '(mouse-wheel-tilt-scroll t)
 '(net-utils-package t)
 '(ns-alternate-modifier (quote meta))
 '(os-utils-package t)
 '(package-get-require-signed-base-updates nil)
 '(package-selected-packages
   (quote
    (docker docker-api docker-compose-mode lua-mode dockerfile-mode browse-at-remote git-link rmsbolt protobuf-mode color-theme date-at-point dired-collapse dired-subtree flx flx-isearch gh gitlab gitlab-ci-mode go-autocomplete go-guru go-impl go-imports go-mode go-rename go-scratch go-stacktracer go-tag god-mode golint graphviz-dot-mode highlight highlight-indent-guides magit magit-filenotify markdown-mode markdown-preview-mode popup popup-complete popup-imenu popup-switcher pyimport flycheck lsp-mode rg yaml-mode window-numbering thrift slime redshank rainbow-delimiters pymacs pylint pyflakes projectile paredit markdown-mode+ magit-push-remote less-css-mode ido-ubiquitous hungry-delete highlight-symbol highlight-indentation header2 gitignore-mode gitconfig-mode gist flymake-cursor flymake flx-ido find-file-in-repository fill-column-indicator expand-region dylan-mode dired+ diff-hl dash-at-point color-theme-solarized cache c-eldoc autopair auto-highlight-symbol auto-complete ag ack-and-a-half)))
 '(paren-mode (quote blink-paren) nil (paren))
 '(prog-modes-package t)
 '(py-align-multiline-strings-p t)
 '(py-imenu-show-method-args-p t)
 '(query-user-mail-address nil)
 '(reftex-package t)
 '(save-place t nil (saveplace))
 '(save-place-file (expand-file-name ".places" user-emacs-directory))
 '(scroll-bar-mode nil)
 '(sh-script-package t)
 '(show-paren-mode t)
 '(show-paren-ring-bell-on-mismatch t)
 '(size-indication-mode t)
 '(slider-package t)
 '(smerge-command-prefix "m")
 '(strokes-package t)
 '(tab-width 4)
 '(text-modes-package t)
 '(time-package t)
 '(tm-package t)
 '(tool-bar-mode nil nil (tool-bar))
 '(truncate-lines t)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(user-full-name "kevin birch")
 '(user-mail-address "kmb@pobox.com")
 '(vc-cc-package t)
 '(vc-package t)
 '(view-process-package t)
 '(viper-package t)
 '(visual-line-mode nil t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "DejaVu Sans Mono"))))
 '(diff-hl-change ((t (:background "blue4" :foreground "blue4"))))
 '(diff-hl-delete ((t (:inherit diff-removed :foreground "red4" :background "red4"))))
 '(diff-hl-insert ((t (:inherit diff-added :foreground "green4" :background "green4"))))
 '(flymake-errline ((t (:inverse-video nil :foreground nil :underline (:color "red" :style wave)))) t)
 '(flymake-infoline ((t (:inverse-video nil :foreground nil :underline "blue"))))
 '(flymake-warnline ((t (:inverse-video nil :foreground nil :underline "yellow"))) t)
 '(which-func ((t (:forground nil)))))
